kind: pipeline
name: example-pipeline
steps:
  - name: compile
    image: hseeberger/scala-sbt:8u212_1.2.8_2.12.9
    commands:
      - sbt compile
    when:
      branch:
        - master
      event:
        - push
        - pull-request

  - name: tests
    image: hseeberger/scala-sbt:8u212_1.2.8_2.12.9
    commands:
      - sbt test
    when:
      branch:
        - master
      event:
        - push
        - pull-request

  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: github-drone-builds
      username: drone
    when:
      status: [ success, failure ]